[package]
name = "find_homopolymers"
version = "0.1.0"
edition = "2024"

[dependencies]
needletail = { version = "0.6.3" }
clap = { version = "4.5.37", features = ["derive"] }
log = { version = "0.4.27" }
simple_logger = { version = "5.0.0" }
